### ISSUE TITLE
“UniEngine”and “RayTracerFacility" which is not   an existing directory.

### ISSUE THREAD

**Issue by jacksea001** [edisonlee0212/PlantArchitect#2]
1 When I was compiling in cmake, I received an error message
{CMake Error at CMakeLists.txt:53 (add_subdirectory):
  add_subdirectory given source "D:/PlantArchitect/../UniEngine" which is not
  an existing directory.
CMake Error at CMakeLists.txt:57 (add_subdirectory):
  add_subdirectory given source "D:/PlantArchitect/../RayTracerFacility"
  which is not an existing directory.} 

2 And did not see UniEngine and RayTracerFacility in the. gitmodules file of PlantArchitect repository

**Comment by edisonlee0212** [comment]
I'm not making any developments on PlantArchitect and UniEngine anymore. All functionalities supported in PlantArchitect are transported into EvoEngine and the EcoSysLab plugin in EvoEngine. Please take a look at that repo. Thanks.
https://github.com/edisonlee0212/EvoEngine
